"""Initial schema

Revision ID: 10d4c7d1dd40
Revises: 
Create Date: 2026-06-28 22:44:10.898558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d4c7d1dd40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('expanded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(name) > 0', name='chk_collections_name_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_name'), 'collections', ['name'], unique=True)
    op.create_index(op.f('ix_collections_uuid'), 'collections', ['uuid'], unique=True)
    op.create_table('environments',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(name) > 0', name='chk_environments_name_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environments_name'), 'environments', ['name'], unique=False)
    op.create_index(op.f('ix_environments_uuid'), 'environments', ['uuid'], unique=True)
    op.create_table('history',
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('response_size', sa.Integer(), nullable=False),
    sa.Column('request_headers', sa.JSON(), nullable=False),
    sa.Column('response_headers', sa.JSON(), nullable=False),
    sa.Column('response_body', sa.String(), nullable=True),
    sa.Column('environment_uuid', sa.String(length=36), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_environment_uuid'), 'history', ['environment_uuid'], unique=False)
    op.create_index(op.f('ix_history_method'), 'history', ['method'], unique=False)
    op.create_index(op.f('ix_history_uuid'), 'history', ['uuid'], unique=True)
    op.create_table('settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('environment_variables',
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environment_id', 'key', name='uq_env_key')
    )
    op.create_index(op.f('ix_environment_variables_environment_id'), 'environment_variables', ['environment_id'], unique=False)
    op.create_index(op.f('ix_environment_variables_uuid'), 'environment_variables', ['uuid'], unique=True)
    op.create_table('folders',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('expanded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(name) > 0', name='chk_folders_name_not_empty'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_collection_id'), 'folders', ['collection_id'], unique=False)
    op.create_index(op.f('ix_folders_name'), 'folders', ['name'], unique=False)
    op.create_index(op.f('ix_folders_uuid'), 'folders', ['uuid'], unique=True)
    op.create_table('requests',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('body_type', sa.String(length=50), nullable=False),
    sa.Column('raw_body', sa.String(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('follow_redirects', sa.Boolean(), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('auth', sa.JSON(), nullable=False),
    sa.Column('form_data', sa.JSON(), nullable=False),
    sa.Column('scripts', sa.String(), nullable=True),
    sa.Column('tests', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("method IN ('GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'HEAD', 'OPTIONS')", name='chk_requests_method_valid'),
    sa.CheckConstraint('length(method) > 0', name='chk_requests_method_not_empty'),
    sa.CheckConstraint('length(url) > 0', name='chk_requests_url_not_empty'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_collection_id'), 'requests', ['collection_id'], unique=False)
    op.create_index(op.f('ix_requests_folder_id'), 'requests', ['folder_id'], unique=False)
    op.create_index(op.f('ix_requests_method'), 'requests', ['method'], unique=False)
    op.create_index(op.f('ix_requests_name'), 'requests', ['name'], unique=False)
    op.create_index(op.f('ix_requests_uuid'), 'requests', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_uuid'), table_name='requests')
    op.drop_index(op.f('ix_requests_name'), table_name='requests')
    op.drop_index(op.f('ix_requests_method'), table_name='requests')
    op.drop_index(op.f('ix_requests_folder_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_collection_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_folders_uuid'), table_name='folders')
    op.drop_index(op.f('ix_folders_name'), table_name='folders')
    op.drop_index(op.f('ix_folders_collection_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_index(op.f('ix_environment_variables_uuid'), table_name='environment_variables')
    op.drop_index(op.f('ix_environment_variables_environment_id'), table_name='environment_variables')
    op.drop_table('environment_variables')
    op.drop_table('settings')
    op.drop_index(op.f('ix_history_uuid'), table_name='history')
    op.drop_index(op.f('ix_history_method'), table_name='history')
    op.drop_index(op.f('ix_history_environment_uuid'), table_name='history')
    op.drop_table('history')
    op.drop_index(op.f('ix_environments_uuid'), table_name='environments')
    op.drop_index(op.f('ix_environments_name'), table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_collections_uuid'), table_name='collections')
    op.drop_index(op.f('ix_collections_name'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
