"""remove unique constraint from collection name

Revision ID: 71a66038c58a
Revises: 10d4c7d1dd40
Create Date: 2026-06-29 00:12:51.005521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a66038c58a'
down_revision: Union[str, Sequence[str], None] = '10d4c7d1dd40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collections_name'), table_name='collections')
    op.create_index(op.f('ix_collections_name'), 'collections', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collections_name'), table_name='collections')
    op.create_index(op.f('ix_collections_name'), 'collections', ['name'], unique=1)
    # ### end Alembic commands ###
